# Generated by Django 5.0.3 on 2024-04-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('manager', 'manager'), ('employee', 'employee')], max_length=30, null=True),
        ),
    ]
