# Generated by Django 5.0.3 on 2024-04-18 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='code_name',
        ),
    ]
