# Generated by Django 5.0.3 on 2024-04-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
