# Generated by Django 5.0.3 on 2024-05-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission_app', '0002_remove_role_code_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(related_name='role_permissions', to='permission_app.permission'),
        ),
    ]
